
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class build
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public build()
    {

        this.blocks = new HashSet<block>();

    }


    public int BuildID { get; set; }

    public Nullable<int> SiteID { get; set; }

    public string Name { get; set; }

    public string Adress { get; set; }

    public string Gps { get; set; }

    public string Properties { get; set; }

    public Nullable<int> CampusID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<block> blocks { get; set; }

    public virtual campu campu { get; set; }

    public virtual site site { get; set; }

}

}
