
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class departmentroom
{

    public int DepartmentRoomID { get; set; }

    public Nullable<int> RoomID { get; set; }

    public Nullable<int> DepartmentID { get; set; }

    public string Other { get; set; }



    public virtual department department { get; set; }

    public virtual room room { get; set; }

}

}
