
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class deviceroom
{

    public int DeviceRoomID { get; set; }

    public Nullable<int> RoomID { get; set; }

    public Nullable<int> DeviceID { get; set; }

    public string LocationX { get; set; }

    public string LocationY { get; set; }

    public Nullable<System.DateTime> CreationDate { get; set; }

}

}
