
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class device
{

    public int DeviceID { get; set; }

    public string Name { get; set; }

    public string Properties { get; set; }

    public string Technology { get; set; }

    public Nullable<int> DeviceTypeID { get; set; }



    public virtual devicetype devicetype { get; set; }

}

}
