
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class room
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public room()
    {

        this.departmentrooms = new HashSet<departmentroom>();

    }


    public int RoomID { get; set; }

    public Nullable<int> FloorID { get; set; }

    public string Name { get; set; }

    public Nullable<int> RoomTypeID { get; set; }

    public string Map { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<departmentroom> departmentrooms { get; set; }

    public virtual floor floor { get; set; }

    public virtual roomtype roomtype { get; set; }

}

}
