
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class senderrecieverdeviceraspberrybeacon
{

    public int ID { get; set; }

    public string DeviceID { get; set; }

    public string CreationDate { get; set; }

    public string Counter { get; set; }

    public string Device_Name_1 { get; set; }

    public string Device_Name_2 { get; set; }

    public string Device_Name_3 { get; set; }

    public string Device_Name_4 { get; set; }

    public string Device_Name_5 { get; set; }

    public string Device_Name_6 { get; set; }

    public string Device_RSS_1 { get; set; }

    public string Device_RSS_2 { get; set; }

    public string Device_RSS_3 { get; set; }

    public string Device_RSS_4 { get; set; }

    public string Device_RSS_5 { get; set; }

    public string Device_RSS_6 { get; set; }

    public string Device_Distance_1 { get; set; }

    public string Device_Distance_2 { get; set; }

    public string Device_Distance_3 { get; set; }

    public string Device_Distance_4 { get; set; }

    public string Device_Distance_5 { get; set; }

    public string Device_Distance_6 { get; set; }

    public string Point_Location { get; set; }

}

}
