
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class useruserrole
{

    public int UserUserRoleID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> UserRoleID { get; set; }



    public virtual user user { get; set; }

    public virtual userrole userrole { get; set; }

}

}
