
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class userdepartment
{

    public int UserDepartmentID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> DepartmentID { get; set; }



    public virtual department department { get; set; }

    public virtual user user { get; set; }

}

}
