
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LocationApp.Data.Database
{

using System;
    using System.Collections.Generic;
    
public partial class usercontact
{

    public int UserContactID { get; set; }

    public string Contact { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> UserContactTypeID { get; set; }



    public virtual user user { get; set; }

    public virtual usercontacttype usercontacttype { get; set; }

}

}
